### ISSUE TITLE
Problem with StopMsgFilter(id)

### ISSUE THREAD

**Issue by tesla20000** [BrianHumlicek/J2534-Sharp#15]
Function StopMsgFilter() for some types of passThru working incorrectly still. 
Sometimes correct logic is put some delay after we call this function, otherwise hardware still is busy / operation is not done, and then function CheckResult catch exception. 
 By the way ... all exceptions details described as "OK" - this is not cool solution :)

About issue... this looks as api can't wait for hardware response about execution this StopMsgFilter. 
In this moment i can work with this ONLY when i use some delay 300mS after.

Different question is why function is more problematic on real car, and when i work ONLY with connected PassThru device, 
function work (i feel ) better/ more stable. 

Summary: this looks like problem with sync threads.
Problem exist for tested by me hardwares: TEXA model 2021 , SVCI , Abrites AVDI.

 public void StopMsgFilter(int FilterId)
        {
            lock (sync)
            {
                API.CheckResult(API.PTStopMsgFilter(channelId, FilterId));
                filterList.RemoveAll(f => f.FilterId == FilterId);
            }
        }

**Comment by BrianHumlicek** [comment]
This is very likely caused by the hardware/driver not being 100% compliant or bugs in the driver.

If we can identify an issue where J2534Sharp is not standard compliant or clearly has an issue, I’ll fix it immediately.  Issues that are hardware specific I’m hesitant to accommodate.  Unless it’s an extremely common variation or very generic, I’m not very inclined to address it.

Brian
