### ISSUE TITLE
No compatible export signature was found in DLL

### ISSUE THREAD

**Issue by autokent** [BrianHumlicek/J2534-Sharp#22]
Sorry, I solved the problem by creating a new project.
And now it works)

**Comment by tesla20000** [comment]
Hi. @autokent -can You say more details please ?
For me now happened same , Win11 64 started on Parallel (MacOS M1), VS2022 , NetFramework 6.0 or 7.0 same issue. 

Here details of exception:
---------
System.MissingMemberException
  HResult=0x80131512
  Message=No compatible export signature was found in DLL C:\Program Files (x86)\PEAK-System\PCAN-PassThru API\04.04\x64\PCANPT32.dll
  Source=J2534-Sharp
  StackTrace:
   at SAE.J2534.APIFactory.GetAPI(String Filename)
   at PassThruXXXX.ConnectionManager.initialiseChannel(Enum protocolId) in C:\Users\xxx\source\repos\PassThruXXXX\PassThruXXXX\ConnectionManager.cs:line 158

  This exception was originally thrown at this call stack:
    [External Code]
    PassThruXXXX.ConnectionManager.initialiseChannel(System.Enum) in ConnectionManager.cs
------------
Additionally - @BrianHumlicek - can You please release new Version maybe? This from nugget is precompiled with NetFramework 4.x , then start warning : 

Warning | NU1701 | Package 'J2534-Sharp 1.0.0-CI00036' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0-windows7.0'. This package may not be fully compatible with your project.

I just think this can be a reason of actual problem. 
Thank You 
Regards
