### ISSUE TITLE
GM lan pin 1 communication..

### ISSUE THREAD

**Issue by IronDuke123** [BrianHumlicek/J2534-Sharp#23]
I did modify this library to work with pin 1 gmlan at 33,3333 baud..  I keep on forgetting to let you know, not sure if others have been trying...
Not sure of the correct way to do it but I added Baud.CAN_33333 to the baud definitions.. 
Connect with SW_CAN_PS protocol and then I specify pin 1 using Channel.SetConfig(Parameter.J1962_PINS, 256);

I think the baud definition is the only thing I changed.. don't remember at the moment, if I can find some notes I'll respond here.

Seems to work ok.. I do have issues switching from VPW and back but I'm sure that's something else on my end.. Need to power cycle the MDI to get it to be able to use pin 1 again...

**Comment by BrianHumlicek** [comment]
When I designed it, I assumed you could use an int with a hard cast in lieu of the enumeration.  It turns out that is mostly true, but you have to use an unchecked wrapper to make the compiler happy.  See this thread for details of how to do it.

https://github.com/BrianHumlicek/J2534-Sharp/issues/17

Regardless, if it is a standard baudrate, I am happy to add it to the base library.  Are there any others that should be added?

Brian

**Comment by IronDuke123** [comment]
Thank you, I just recently sorta figured out how to use cast.. lol.. I'll try that next time.. 
for GM it is a very standard baudrate from 2007 and up to current year.. Pin 1 low speed lan.. 
As far as other speeds I think you have it covered. you even have the 4x vpw for high speed on pin 2.. 
Thanks again for this!!!!

**Comment by BrianHumlicek** [comment]
I added an enum value for this.
