### ISSUE TITLE
Where is the API 2.02 enumeration ?

### ISSUE THREAD

**Issue by Elmue** [BrianHumlicek/J2534-Sharp#6]
You write that you support the 2.02 API.
But I cannot see where you enumerate them.
You only use the registry key "PassThruSupport.04.04"

For example the device name ist stored under
Version 04.04:
HKLM/Software/PassThruSupport.04.04/Vendor[VendorIndex]/Name

Version 02.02:
HKLM/Software/PassThru_Support/Vendor[VendorIndex]/Devices/Device[DeviceIndex]/Name

This J2534 API is a horrible misdesign!

By the way: You can make your code easier by not using WOW6432Node:

using (RegistryKey i_HKLM = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32))

which will always enumerate the 32 view of the registry which is WOW6432Node on a 64 bit Windows.

**Comment by BrianHumlicek** [comment]
I also wrote under TODO: Test with an actual 2.02 driver...

The statement about supporting v2.02 was aimed at the fact that I shim the 2.02 api to behave as a 4.04 API so either .DLL can be loaded and consumed without having knowledge of which version you actually have.  Also, you can load a DLL directly without enumerating the registry, which is how I typically have done things.

Since you feel this API is such a "horrible misdesign", I don't recommend you use it or fork it.
