### ISSUE TITLE
library usage.. I used your code for something of my own

### ISSUE THREAD

**Issue by IronDuke123** [BrianHumlicek/J2534-Sharp#8]
Hi, this isn't an issue or a problem.. You did state in the readme you wanted feedback on it's use though..
I did not find an email or other contact info so I did this instead?
I have used your dll with my code as a brute force program for GM E38 ecu's..  Please see the link below, I did put your copy write info in the main code, not sure if I need to do anything else for you?? 
https://github.com/IronDuke123/E38_brute_force

Thanks for this library!!!  getting used to it, still want to figure out how to send data other than using new byte every time.. Can I send a string? a word? etc.. that's on me, I am still learning..

**Comment by BrianHumlicek** [comment]
Thank you for the feedback.  Its always good to hear about how it is being used.  I actually did recently browse through your repo, and looked at what you were doing.  My email is my name at gmail.

If you wanted to use a string instead of bytes, I think you could use something like Channel.SendMessage(Encoding.GetBytes("String to send"));
